pipeline_config:
    project: test-project
    display_name: test-display-name
    pipeline_root: gs://test-bucket/test-display-name
    parameter_values:
        n: 10
component_config:
    target_image: us-docker.pkg.dev/test-project/test-repository/multi_component_test:latest
    packages_to_install:
        - numpy