# PIPELINE DEFINITION
# Name: python-containerized-test
# Inputs:
#    config: dict
# Outputs:
#    component-mean_value: system.Metrics
components:
  comp-component:
    executorLabel: exec-component
    inputDefinitions:
      parameters:
        config:
          parameterType: STRUCT
    outputDefinitions:
      artifacts:
        mean_value:
          artifactType:
            schemaTitle: system.Metrics
            schemaVersion: 0.0.1
        sample_dataset:
          artifactType:
            schemaTitle: system.Dataset
            schemaVersion: 0.0.1
deploymentSpec:
  executors:
    exec-component:
      container:
        args:
        - --executor_input
        - '{{$}}'
        - --function_to_execute
        - component
        command:
        - sh
        - -c
        - "\nif ! [ -x \"$(command -v pip)\" ]; then\n    python3 -m ensurepip ||\
          \ python3 -m ensurepip --user || apt-get install python3-pip\nfi\n\nPIP_DISABLE_PIP_VERSION_CHECK=1\
          \ python3 -m pip install --quiet --no-warn-script-location 'numpy' && \"\
          $0\" \"$@\"\n"
        - python3
        - -m
        - kfp.dsl.executor_main
        image: us-west2-docker.pkg.dev/pg-cvs-sandbox/demo-repository/example_py_containerized:latest
pipelineInfo:
  name: python-containerized-test
root:
  dag:
    outputs:
      artifacts:
        component-mean_value:
          artifactSelectors:
          - outputArtifactKey: mean_value
            producerSubtask: component
    tasks:
      component:
        cachingOptions:
          enableCache: true
        componentRef:
          name: comp-component
        inputs:
          parameters:
            config:
              componentInputParameter: config
        taskInfo:
          name: component
  inputDefinitions:
    parameters:
      config:
        parameterType: STRUCT
  outputDefinitions:
    artifacts:
      component-mean_value:
        artifactType:
          schemaTitle: system.Metrics
          schemaVersion: 0.0.1
schemaVersion: 2.1.0
sdkVersion: kfp-2.3.0
