pipeline_config:
    project: test-project
    display_name: test-display-name
    pipeline_root: gs://test-bucket/test-display-name
    parameter_values:
        n: 10
component_config:
    component_name: test_custom_component
    base_image: python:3.9
    target_image: us-docker.pkg.dev/test-project/test-repository/test_custom_component:latest
    packages_to_install:
        - numpy
        - pandas
        - gcsfs
        - fastparquet